### PR TITLE
Rename runtime

### PR DESCRIPTION
**Pull request by ebassi**
https://phabricator.endlessm.com/T15504

### CODE REVIEW

**Comment by ptomato** [comment]
There are a few places left where the old name is used:
- in `.gitignore`
- in the "subject" argument to flatpak-builder
- as a dependency of the `check` rule (this is what's causing the Travis failure)

**Review by ptomato — CHANGES_REQUESTED** [review]
comment above

**Comment by ebassi** [comment]
Updated the PR.

**Review by ptomato — APPROVED** [review]
**CR pass**

**Pull request merged**
